name: super-linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses : actions/checkout@v3

     - name : Run super-linter
       user: github/super-linter@v3
       env :
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
